
DO NOT USE THIS article as of 2019-04-15
WAITING ON RESPONSE from support
associated with https://cloudbees.atlassian.net/browse/CORE-517


== Enhanced Credentials Management

https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-secure-guide/enhanced-credentials-masking[Enhanced credentials masking] is a CloudBees plugin that is not installed by default used to mask credential variables and values used outside of `withCredentials( …​ ) { …​ }` pipeline blocks, thereby maintaining the security and secrecy of such credentials.

NOTE: This feature is only supported with CloudBees CI controllers.

In order to use this feature:

. Verify that the CloudBees Enhanced Credentials Masking Plugin is installed on your CloudBees CI controller. If it is not, install it through `Manage Jenkins` -> `System Configuration` -> `Manage Plugins` -> `Available`.
. Go to the `Manage Jenkins` area of your CloudBees CI controller.
. On the `Manage Jenkins` page, click `Configure Global Security` under the `Security` section.
. On the resulting `Configure Global Security` page, scroll down to the `CloudBees Enhanced Credentials Masking Plugin` section and select the *Enable extended masking of credentials* check box.
. Scroll to the end of the page and click the `Save` button.
